# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ production ]

jobs:
  build_linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build package
      run: |
        pip install wheel numpy twine
        chmod +x travis/build-wheels.sh
        touch requirements.txt
        export DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
        export PLAT=manylinux2010_x86_64
        docker pull quay.io/pypa/manylinux2010_x86_64
        docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
        ls wheelhouse/
        twine upload wheelhouse/* --skip-existing -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}

  build_macos:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build package
      run: |
        pip install pathlib
        pip install wheel numpy twine
        python setup.py sdist bdist_wheel
        mkdir wheelhouse
        cp -a dist/. wheelhouse/
        ls wheelhouse/
        twine upload wheelhouse/* --skip-existing -u ${{ secrets.PYPI_USER }} -p ${{ secrets.PYPI_PASSWORD }}
